name: GitHub Actions Pipeline
run-name: ${{ github.actor }} is testing out battleships build 🛳
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: jirutka/setup-alpine@v1
        with:
          go-version: '1.23.0'
      - name: Unit tests
        run: |
          go get -u github.com/stretchr/testify
          go test ./...
      - name: Build
        run: |
          cd cmd
          go build
  Analyse:
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.3.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=gobattleships
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
