name: GitHub Actions Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  BattleshipsPipeline:
    runs-on: golang:1.23
    steps:
      - name: Unit tests
        run: |
          go get -u github.com/stretchr/testify
          go test ./...
      - name: Build
        run: |
          cd cmd
          go build
