name: GitHub Actions Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Unit tests
        run: |
          go mod download github.com/stretchr/testify
          go get github.com/stretchr/testify/assert@v1.7.0
          go test ./...
      - name: Build
        run: |
          cd cmd
          go build
